spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-69.railway.app:8058/railway
    username: postgres
    password: BcVOOT32bYcYuSa0Opqx
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate